spring:
  application:
    name: booting
---
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 9090
---

spring:
  config:
    activate:
      on-profile: test

server:
  port: 9080

---
